name: HEROKU CI
env:
    APP_NAME: ${{ 'fakebook-fake-facebook' }}
    EMAIL: ${{'pawel.jakub.wojcik@gmail.com'}}
    HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

on:
    push:
        branches: [production]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Config git
              run: git config --global user.name "Automated Heroku Deploy" && git config --global user.email ${{env.EMAIL}}
            - name: create login file
              run: |
                  cat > ~/.netrc <<EOF
                    machine api.heroku.com
                      login ${{env.EMAIL}}
                      password ${{env.HEROKU_API_KEY}}
                    machine git.heroku.com
                      login ${{env.EMAIL}}
                      password ${{env.HEROKU_API_KEY}}
                  EOF
            - name: Login to heroku
              run: heroku login
            - name: Choosing app
              run: heroku git:remote -a ${{env.APP_NAME}}

            - name: Pushing build to heroku git
              run: git push heroku `git subtree split --prefix=server production`:refs/heads/master
