name: HEROKU CI
env:
  APP_NAME: ${{ 'fakebook-fake-facebook' }}
  EMAIL: ${{'pawel.jakub.wojcik@gmail.com'}}


on:
    push:
        branches: [production]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Config git
              run: git config --global user.name "Automated Heroku Deploy" && git config --global user.email ${{env.EMAIL}}
            - name: Login to heroku
              run: heroku login 
              
            - name: Pushing build to heroku git
              run: git push heroku `git subtree split --prefix=server production`:refs/heads/master
