name: HEROKU CI
env:
    APP_NAME: ${{ 'fakebook-fake-facebook' }}
    EMAIL: ${{'pawel.jakub.wojcik@gmail.com'}}
    HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

on:
    push:
        branches: [production]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fakebook-fake-facebook
          heroku_email: pawel.jakub.wojcik@gmail.com
          justlogin: true
      - run: heroku auth:whoami
