
name: HEROKU CI

on:
  push:
    branches: [ production ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          app-name: "fakebook-fake-facebook"
          heroku_email: "pawel.jakub.wojcik@gmail.com"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          appdir: "./server"
          branch: "production"
    
